# Generated by Django 4.1.1 on 2022-09-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0002_remove_person_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SauceQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_sauce', models.BooleanField(default=False)),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.sandwich')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.sauce')),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='sauces',
            field=models.ManyToManyField(through='CPLN.SauceQuantity', to='CPLN.sauce'),
        ),
    ]
