# Generated by Django 4.1.1 on 2022-09-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0003_sandwich_sauce_saucequantity_sandwich_sauces'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='sin direccion', max_length=100),
        ),
    ]
