# Generated by Django 4.1.1 on 2022-09-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0004_dailycard_person_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
