# Generated by Django 4.1.1 on 2022-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0005_remove_person_age_person_dateofbirth_person_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saucequantity',
            name='sandwich',
        ),
        migrations.RemoveField(
            model_name='saucequantity',
            name='sauce',
        ),
        migrations.AlterField(
            model_name='dailycard',
            name='img',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Sandwich',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='SauceQuantity',
        ),
    ]
