# Generated by Django 4.1.1 on 2022-09-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0007_remove_attendance_lunchroom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpage',
        ),
    ]
