# Generated by Django 4.1.1 on 2022-09-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0008_delete_userpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
