# Generated by Django 4.1.1 on 2022-09-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0010_neighborhood_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='number',
        ),
    ]
