# Generated by Django 4.1.1 on 2022-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0011_remove_person_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='No hay peticiones expecificas', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='dailycard',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
