# Generated by Django 4.1.1 on 2022-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0012_listfood_dailycard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
