# Generated by Django 4.1.1 on 2022-10-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0013_alter_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='last_update',
        ),
    ]
