# Generated by Django 4.1.1 on 2022-10-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0015_candidate_rename_dailycard_news_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
