# Generated by Django 4.1.1 on 2022-10-05 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0016_rename_news_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListFood',
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_candidate',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.neighborhood', verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.CharField(max_length=1000, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
    ]
