# Generated by Django 4.1.1 on 2022-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0016_rename_news_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListFood',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_candidate',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
