# Generated by Django 4.1.1 on 2022-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0017_delete_listfood_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(default='Sin Título', max_length=100, verbose_name='Título'),
        ),
    ]
