# Generated by Django 4.1.1 on 2022-10-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0018_alter_new_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('P', 'Postulado'), ('R', 'Rechazado'), ('An', 'Analizando'), ('Ac', 'Aceptado')], default='P', max_length=2, verbose_name='Estado'),
        ),
    ]
