# Generated by Django 4.1.1 on 2022-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0019_candidate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='No hay peticiones expecíficas', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Lista de Comida',
                'verbose_name_plural': 'Lista de Comida',
            },
        ),
    ]
