# Generated by Django 4.1.1 on 2022-10-13 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0020_listfood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listfood',
            options={'verbose_name': 'Lista de Alimentos', 'verbose_name_plural': 'Lista de Alimentos'},
        ),
        migrations.AlterField(
            model_name='listfood',
            name='description',
            field=models.TextField(default='No hay peticiones específicas', verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dateOfBirth', models.DateField(default=datetime.date.today, verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.neighborhood', verbose_name='Barrio')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
            },
        ),
    ]
