# Generated by Django 4.1.1 on 2022-10-18 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0021_alter_listfood_options_alter_listfood_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Apellido'),
        ),
    ]
