# Generated by Django 4.1.1 on 2022-10-18 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0025_alter_volunteer_first_name_alter_volunteer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z+\\w]*$', 'Solamente está permitido usar caracteres alfabéticos.'), django.core.validators.MinLengthValidator(3)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z+\\w]*$', 'Solamente está permitido usar caracteres alfabéticos.'), django.core.validators.MinLengthValidator(3)], verbose_name='Apellido'),
        ),
    ]
