# Generated by Django 4.1.1 on 2022-10-18 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0029_alter_candidate_first_name_alter_candidate_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solamente está permitido usar caracteres numéricos.'), django.core.validators.MinLengthValidator(8)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solamente está permitido usar caracteres numéricos.'), django.core.validators.MinLengthValidator(8)], verbose_name='Teléfono'),
        ),
    ]
