# Generated by Django 4.1.1 on 2022-10-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0031_remove_candidate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator', models.CharField(default='Anónimo', max_length=40, verbose_name='Donante')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de donación')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Almuerzo',
                'verbose_name_plural': 'Almuerzos',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Sin orígen', max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Orígen',
                'verbose_name_plural': 'Orígenes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de producto',
                'verbose_name_plural': 'Tipos de productos',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40, verbose_name='Rol')),
                ('description', models.CharField(default=' ', max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de retiro')),
                ('id_familygiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadora', to='CPLN.family', verbose_name='Familia dadora')),
                ('id_familyreciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptora', to='CPLN.product', verbose_name='Familia receptora')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.product', verbose_name='Producto')),
                ('id_withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.withdrawal', verbose_name='Retiro')),
            ],
            options={
                'verbose_name': 'Detalle del retiro',
                'verbose_name_plural': 'Detalle de los retiros',
            },
        ),
        migrations.CreateModel(
            name='ProductDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('id_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.donation', verbose_name='Donación')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Donación de productos',
                'verbose_name_plural': 'Donaciones de productos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='id_product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.producttype', verbose_name='Tipo de producto'),
        ),
        migrations.CreateModel(
            name='MonetaryDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Monto')),
                ('id_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.origin', verbose_name='Orígen')),
            ],
            options={
                'verbose_name': 'Donación monetaria',
                'verbose_name_plural': 'Donaciones monetarias',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('id_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.family', verbose_name='Familia')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventorio',
                'verbose_name_plural': 'Inventorios',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('id_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.lunch', verbose_name='Almuerzo')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='FamilyVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.family', verbose_name='Familia')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.role', verbose_name='Rol')),
                ('id_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.volunteer', verbose_name='Voluntario')),
            ],
            options={
                'verbose_name': 'Inventorio',
                'verbose_name_plural': 'Inventorios',
            },
        ),
    ]
