# Generated by Django 4.1.1 on 2022-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0032_donation_family_lunch_origin_product_producttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('P', 'Postulado'), ('R', 'Rechazado'), ('An', 'Analizando'), ('Ac', 'Aceptado')], default='P', max_length=2, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CPLN.candidate',),
        ),
    ]
