# Generated by Django 4.1.1 on 2022-10-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0034_alter_ingredient_id_lunch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Voluntario', 'verbose_name_plural': 'Voluntarios'},
        ),
    ]
