# Generated by Django 4.1.1 on 2022-11-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0036_product_unit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyvolunteer',
            options={'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
    ]
