# Generated by Django 4.1.1 on 2022-11-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0039_remove_familyvolunteer_id_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyvolunteer',
            old_name='id_family',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='familyvolunteer',
            old_name='id_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='familyvolunteer',
            old_name='id_volunteer',
            new_name='volunteer',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='id_lunch',
            new_name='lunch',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='id_family',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='monetarydonation',
            old_name='id_origin',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_product_type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='productdonation',
            old_name='id_donation',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='productdonation',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='id_familygiver',
            new_name='familygiver',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='id_familyreciever',
            new_name='familyreciever',
        ),
        migrations.RenameField(
            model_name='withdrawaldetail',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='withdrawaldetail',
            old_name='id_withdrawal',
            new_name='withdrawal',
        ),
    ]
