# Generated by Django 4.1.1 on 2022-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0040_alter_neighborhood_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha de donación'),
        ),
    ]
