# Generated by Django 4.1.1 on 2022-11-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0041_alter_donation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunch',
            options={'verbose_name': 'Menú', 'verbose_name_plural': 'Menús'},
        ),
    ]
