# Generated by Django 4.1.1 on 2022-11-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0042_alter_lunch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario'},
        ),
    ]
