# Generated by Django 4.1.1 on 2022-11-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0040_rename_id_family_familyvolunteer_family_and_more'),
        ('CPLN', '0043_alter_inventory_options'),
    ]

    operations = [
    ]
